CREATE DATABASE IF NOT EXISTS iot2;

use iot2;

CREATE TABLE IF NOT EXISTS board (
no INT AUTO_INCREMENT NOT NULL,
name VARCHAR(10),
subject VARCHAR(30),
email VARCHAR(30),
contents TEXT,
password VARCHAR(10),
date DATETIME DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY(no)
);