
CREATE DATABASE IF NOT EXISTS board;

CREATE TABLE IF NOT EXISTS ARTICLE (
no INT AUTO_INCREMENT NOT NULL,
name VARCHAR(10),
subject VARCHAR(30),
comment TEXT,
passwd VARCHAR(20),
date VARCHAR(20),
email VARCHAR(20),
count int DEFAULT '0',
PRIMARY KEY(no)
);